apiVersion: v1
kind: ConfigMap
metadata:
  name: vegeta-payload
  namespace: demo
data:
  payload: |
    GET http://backend.demo.svc.cluster.local?sleep=100
---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
  namespace: demo
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app: load-test
      annotations:
        sidecar.istio.io/inject: "INJECT"
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      containers:
        - name: vegeta
          image: quay.io/rlehmann/vegeta/v12
          command: ["/bin/bash", "-c"]
          args:
            - "/ko-app/v12 -cpus=1 attack -duration=1m -rate=2000/1s -targets=/var/vegeta/payload | /ko-app/v12 report -every 10s"
          resources:
            requests:
              cpu: 1000m
              memory: 3Gi
          volumeMounts:
            - name: vegeta-payload
              mountPath: /var/vegeta
      volumes:
        - name: vegeta-payload
          configMap:
            name: vegeta-payload
      restartPolicy: Never
